version: '3'
services:
  producer:
    build:
      context: ./azurekafkaproducer
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    image: producer:latest
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=AZURE_EVENT_HUB_NAMESPACE_NAME_HERE.servicebus.windows.net:9093
      - KAFKA_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="\$\ConnectionString" password="AZURE_EVENT_HUB_CONNECTION_STRING_HERE";

  consumer:
    build:
      context: ./azurekafkaconsumer
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    image: consumer:latest
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=AZURE_EVENT_HUB_NAMESPACE_NAME_HERE.servicebus.windows.net:9093
      - KAFKA_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="\$\ConnectionString" password="AZURE_EVENT_HUB_CONNECTION_STRING_HERE";