networks:
  kafka-local:
    driver: bridge

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    networks:
      - kafka-local
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:3.4'
    networks:
      - kafka-local
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
      
  producer:
    build:
      context: ./azurekafkaproducer
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    image: producer:latest
    networks:
      - kafka-local
    depends_on:
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC_NAME={TOPIC_NAME}

  consumer:
    build:
      context: ./azurekafkaconsumer
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    image: consumer:latest
    networks:
      - kafka-local
    depends_on:
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC_NAME={TOPIC_NAME}
      - GROUP_ID={GROUP_ID_NAME}